/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ku6Sf4rtBvc4dQ1SyEoEgQ
// Component: CktnmCyKNbEc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ContentTitle from "../../ContentTitle"; // plasmic-import: jU6e8T6oRosp/component
import NewsCard from "../../NewsCard"; // plasmic-import: wmCnuxcQdxPB/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ku6Sf4rtBvc4dQ1SyEoEgQ/projectcss
import sty from "./PlasmicMainContent.module.css"; // plasmic-import: CktnmCyKNbEc/css

createPlasmicElementProxy;

export type PlasmicMainContent__VariantMembers = {};
export type PlasmicMainContent__VariantsArgs = {};
type VariantPropType = keyof PlasmicMainContent__VariantsArgs;
export const PlasmicMainContent__VariantProps = new Array<VariantPropType>();

export type PlasmicMainContent__ArgsType = {};
type ArgPropType = keyof PlasmicMainContent__ArgsType;
export const PlasmicMainContent__ArgProps = new Array<ArgPropType>();

export type PlasmicMainContent__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  contentTitle?: Flex__<typeof ContentTitle>;
  newsCard?: Flex__<typeof NewsCard>;
};

export interface DefaultMainContentProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMainContent__RenderFunc(props: {
  variants: PlasmicMainContent__VariantsArgs;
  args: PlasmicMainContent__ArgsType;
  overrides: PlasmicMainContent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__ui1Ts)}>
        <PlasmicImg__
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: "/plasmic/minimalist_about_me_page/images/pxl202504121752363841Jpg.jpg",
            fullWidth: 2000,
            fullHeight: 2000,
            aspectRatio: undefined
          }}
        />
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__whJzy)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__cr16P
          )}
        >
          <React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#FFFFFF" }}
            >
              {"We are an indie game studio developing "}
            </span>
            <React.Fragment>{""}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "var(--token-c4GqJ_Pt1ean)", fontWeight: 700 }}
            >
              {"immersive 3D"}
            </span>
            <React.Fragment>{""}</React.Fragment>
            <span
              className={"plasmic_default__all plasmic_default__span"}
              style={{ color: "#FFFFFF" }}
            >
              {" games."}
            </span>
          </React.Fragment>
        </div>
        <ContentTitle
          data-plasmic-name={"contentTitle"}
          data-plasmic-override={overrides.contentTitle}
          className={classNames("__wab_instance", sty.contentTitle)}
          title={"Latest News"}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__w2DNe
          )}
        >
          {"Stay updated with our latest announcements and events"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__rbZl1)}>
        {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))([
          2, 3, 4
        ]).map((__plasmic_item_0, __plasmic_idx_0) => {
          const currentItem = __plasmic_item_0;
          const currentIndex = __plasmic_idx_0;
          return (
            <div
              className={classNames(projectcss.all, sty.freeBox__hlKTw)}
              key={currentIndex}
            >
              <NewsCard
                data-plasmic-name={"newsCard"}
                data-plasmic-override={overrides.newsCard}
                className={classNames("__wab_instance", sty.newsCard)}
                date={"Test123"}
                description={"Das ist eine Beschreibung"}
                title={"Titel"}
                url={`/`}
              />
            </div>
          );
        })}
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__dMlDv
        )}
      >
        {
          "                                                                                                                                                                       "
        }
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__uvv7G)}>
        <div className={classNames(projectcss.all, sty.freeBox__aj5A)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__g5I7
            )}
          >
            {"Logo"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uuyBu
            )}
          >
            {
              "Creating immersive gaming experiences that push the boundaries of creativity and innovation."
            }
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uDw7L
            )}
          >
            {"Social meidia logos"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__eWxtv)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___1UqS
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ fontWeight: 700 }}
              >
                {"Quick links"}
              </span>
            </React.Fragment>
          </div>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__mpFo7
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Games"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__kY1WM
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"News"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__bLsQo
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"About Us"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__m0O89
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Careers"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___8UO9R
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Press Kit"}
          </PlasmicLink__>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__veEvm)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__gptcv
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ fontWeight: 700 }}
              >
                {"Games"}
              </span>
            </React.Fragment>
          </div>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__gTlkp
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Never Stop Drawing"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___3AkB0
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Upcoming Projects"}
          </PlasmicLink__>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__eBpl1)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__drLpx
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{ fontWeight: 700 }}
              >
                {"Contact"}
              </span>
            </React.Fragment>
          </div>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__lSSe
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Berlin, Germany"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___1Cxzn
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"hi@atricas.com"}
          </PlasmicLink__>
        </div>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__qftfV
        )}
      >
        {
          "                                                                                                                                                                       "
        }
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__xf5B0)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___3WCK
          )}
        >
          {"(c) 2025 atricas. All rights reserved."}
        </div>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___87RaL)}
        >
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___90IO
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Privacy Policy"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link___5W4S3
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Terms of Service"}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__w8DQz
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"nextjs"}
          >
            {"Cookie Policy"}
          </PlasmicLink__>
        </Stack__>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "contentTitle", "newsCard"],
  img: ["img"],
  contentTitle: ["contentTitle"],
  newsCard: ["newsCard"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  contentTitle: typeof ContentTitle;
  newsCard: typeof NewsCard;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMainContent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMainContent__VariantsArgs;
    args?: PlasmicMainContent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMainContent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMainContent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMainContent__ArgProps,
          internalVariantPropNames: PlasmicMainContent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMainContent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMainContent";
  } else {
    func.displayName = `PlasmicMainContent.${nodeName}`;
  }
  return func;
}

export const PlasmicMainContent = Object.assign(
  // Top-level PlasmicMainContent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    contentTitle: makeNodeComponent("contentTitle"),
    newsCard: makeNodeComponent("newsCard"),

    // Metadata about props expected for PlasmicMainContent
    internalVariantProps: PlasmicMainContent__VariantProps,
    internalArgProps: PlasmicMainContent__ArgProps
  }
);

export default PlasmicMainContent;
/* prettier-ignore-end */
